# Build stage
FROM node:25-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .

# Run stage
FROM node:25-alpine
WORKDIR /app

# Criar um usuário não-root para segurança
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodejs -u 1001

# Copiar os arquivos do estágio de build
COPY --from=build /app ./
USER nodejs
EXPOSE 3000
CMD ["npm", "start"]