services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: rf-app-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - prod-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: rf-nginx-prod
    ports:
      - "80:80"
      - "443:443" # Adiciona a porta 443 para HTTPS
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs # Adiciona o volume para os certificados SSL
      
    depends_on:
      - app
    networks:
      - prod-network
    restart: unless-stopped

networks:
  prod-network:
    driver: bridge