server {
    listen 80;
    server_name localhost aula.dev aula.127.0.0.1.sslip.io;

    location / {
        # Nome do serviço definido no docker-compose e a porta interna
        proxy_pass http://app:3000;
    }

}