server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri; # Redireciona para HTTPS

}

server {
    listen 443 sll;
    server_name _;

    ssl_certificate /etc/nginx/certs/cert.pem; # Caminho para o certificado SSL
    ssl_certificate_key /etc/nginx/certs/key.pem; # Caminho para a chave SSL
    ssl_protocols TLSv1.2 TLSv1.3; # Protocolos SSL suportados

    location / {
        proxy_pass http://app:3000;
    }

}